spring.application.name=snippet-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/snippet_service_db
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:postgres}

app.database.schema=snippet_service

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=${app.database.schema}
spring.jpa.open-in-view=false

spring.flyway.default-schema=${app.database.schema}
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
