spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

spring.cloud.gateway.server.webflux.routes[0].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service-users
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/users/**

spring.cloud.gateway.server.webflux.routes[2].id=snippet-service-snippets
spring.cloud.gateway.server.webflux.routes[2].uri=lb://snippet-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/snippets/**

spring.cloud.gateway.server.webflux.routes[3].id=snippet-service-languages
spring.cloud.gateway.server.webflux.routes[3].uri=lb://snippet-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/languages/**

spring.cloud.gateway.server.webflux.routes[4].id=snippet-service-shares
spring.cloud.gateway.server.webflux.routes[4].uri=lb://snippet-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/shares/**

spring.cloud.gateway.server.webflux.routes[5].id=execution-service-executions
spring.cloud.gateway.server.webflux.routes[5].uri=lb://execution-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/executions/**

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=${GATEWAY_CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,gateway
